name: "Packer Build"
on:
  push:
    branches:
      - master
      - main
  pull_request:
permissions:
      id-token: write # This is required for aws oidc connection
      contents: read # This is required for actions/checkout
      pull-requests: write # This is required for gh bot to comment PR
env:
  TF_LOG: INFO
  AWS_REGION: ${{ secrets.AWS_REGION }}
  PRODUCT_VERSION: "1.11.2"
  
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GitHub-OIDC-TERRAFORM

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Run `packer init`
        id: init
        run: "packer init ./windows.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: "packer validate ./windows.pkr.hcl"

      - name: Run `packer build`
        id: build
        run: |
          packer build ./windows.pkr.hcl | tee build_output.txt
          AMI_ID=$(grep -oP 'ami-\w+' build_output.txt | tail -1)
          echo "AMI_ID=$AMI_ID" >> $GITHUB_ENV

      - name: Update SSM Parameter
        run: |
          aws ssm put-parameter --name "/halon/packer/windows/image" --value "${{ env.AMI_ID }}" --type "String" --overwrite